### ISSUE TITLE
[REFACTOR] Switch from relative path to full path imports

### ISSUE THREAD

**Issue by KiritchoukC** [KiritchoukC/power_progress#71]
I suggest to add switching from `../../widgets` to `package:power_progress/widgets` and similar for imports of your own package.

Incase you ever want to move a file/folder without having to update all of those.

_Originally posted by @VitoMinheere in https://github.com/KiritchoukC/power_progress/issues/66#issuecomment-633284452_

**Comment by VitoMinheere** [comment]
Started on this in https://github.com/VitoMinheere/power_progress/tree/refactor/full-path-imports

There are a lot of files to update. Where did you base the architecture on?

**Comment by KiritchoukC** [comment]
It started as a clean architecture but I switched to DDD because it suited the project better.

It's not completely dry though, that's why there's an issue about finishing the DDD conversion. #66

**Comment by KiritchoukC** [comment]
https://dartcode.org/releases/v3-11/#v3110-2020-05-29

Maybe that could help.
